### ISSUE TITLE
Incompatibility with Blind's Music Discs

### ISSUE THREAD

**Issue by HaipaDev** [magistermaks/mod-redbits#17]
Hey, really great mod, love to see more intriguing redstone component, unfortunately its somehow incompatible with [Blind's Music Discs](https://modrinth.com/mod/blinds-music-discs) I was looking forward to more C418 music discs but oh well
I already submitted an [issue on their side](https://github.com/theblindband/BlindsMusicDiscs/issues/2)
Crash log: https://pastebin.com/bxuPYNAc

**Comment by magistermaks** [comment]
This should be fixed with commit 82eaf61c88011d9af3aff60c25ce95aaa02dabbd (for RedBits 1.16.4)
