### ISSUE TITLE
1.16.4 World crash

### ISSUE THREAD

**Issue by WarAndroid** [magistermaks/mod-redbits#2]
I just downloaded this mod and opened creative world to test it, then when I tested mechanics of redstone latch, I found out that if you place 2 of them connected, place redstone dust next to one, then switch one of them into a different mode, game crashes. If you want to I can send my mod list and crash log.

**Comment by magistermaks** [comment]
Thanks for reporting! The issue should now be resolved. I will publish new version to curseforge later today.
