### ISSUE TITLE
Another latch crash

### ISSUE THREAD

**Issue by WarAndroid** [magistermaks/mod-redbits#3]
I just downloaded a new version of the mod and tested it, I put redstone latch and connected both ends to itself and nothing happened. So I tried with an inverter at one end and then game crashes again (in order to replicate this you need to change the state of latch)

**Comment by WarAndroid** [comment]
Also another crash with latch. Place a latch connect redstone dust to it and click it again

**Comment by WarAndroid** [comment]
game now crashes when anything connected to latch is updated ._.

**Comment by magistermaks** [comment]
I actually have problems with replicating the issues this time, could you send me the full game log and screen shot of the problematic setup? Because I'm clicking and placing those latches all around and nothing crashes

**Comment by magistermaks** [comment]
OK, after some more testing I found the problem and fixed it. The new file on curseforge has the same name as the old one (red-bits-1.4.0). I will leave this issue open for a couple of days - just in case
